### PR TITLE
Create a new pane if none exists

### PR DESCRIPTION
**Pull request by antstorm**
Hi,

Just installed this amazing plugin and I'm really digging it. The only thing that annoys me is that in order to move a file I'm working on to a separate pane I need to create a pane first and then move the file.

With this small change whenever you are switching to a non-existing pane it will create one. Also moving/cloning a file to a non-existing pane will create one.

### CODE REVIEW

**Comment by adzenith** [comment]
This looks good to me. I'm thinking some people might find the change to be unexpected, but this is also sensible enough that I think it'll be ok. I'll merge. Thanks!

**Comment by dmarienko** [comment]
Hi, it's really unexpected behaviour after update !!!
Is it possible to add something like configurable parameter to get it back ??

**Comment by adzenith** [comment]
Yeah, it'd be pretty easy to add a setting.

**Comment by adzenith** [comment]
I'll take a look tonight.

**Comment by dmarienko** [comment]
Thanks !

**Comment by dylanfisher** [comment]
I agree that this is very unexpected behavior. Keeping the default behavior and adding a parameter to `create_pane_if_empty` makes more sense to me, since this requires explicitly enabling new behaviors.

**Comment by adzenith** [comment]
I guess I just thought that nobody would be moving in directions where there aren't panes!

**Comment by dylanfisher** [comment]
I constantly switch between panes and if I'm not sure which pane has focus, it's easier to just move to the pane without checking. Now, I end up with a bunch of empty panes that I have to go and delete. Just to be clear, this is when using the `travel_to_pane` command. 

Thanks for a great plugin by the way :+1:

**Comment by adzenith** [comment]
Please comment on #89. Sorry for the troubles!

**Comment by FichteFoll** [comment]
>if I'm not sure which pane has focus

You certainly need https://packagecontrol.io/packages/InactivePanes.

**Comment by adzenith** [comment]
Haha yet another thing that I added to Origami that had everyone rushing to the issues page. Thanks again for fixing it up @FichteFoll.

**Pull request merged**
