### PR TITLE
Add an argument to create new panes when necessary

### PR DESCRIPTION
**Pull request by adzenith**

### CODE REVIEW

**Comment by antstorm** [comment]
Nice one, @adzenith! Sorry for breaking this behaviour in the first place. I didn't thought that people are moving a lot to empty panes.

**Comment by antstorm** [comment]
Btw, doesn't it make more sense to extract this into `sublime-settings`?

**Comment by adzenith** [comment]
I'm not sure. It seems like you might want different keybindings to do different things, potentially. You can change the keybindings instead of a global setting. What do you think?

**Comment by adzenith** [comment]
I should probably add `create_new_if_necessary=False` to the keybindings so it's obvious.

**Comment by antstorm** [comment]
While putting this option into keybindings is certainly much more flexible solution, but I'm just not sure if anyone would assign different keybindings for that… feels more like one or the other.

Although I'm perfectly fine with putting this into keybindings.

**Comment by adzenith** [comment]
Okay, let's make it a preference then :) I won't have a chance to look at it until tonight if anyone is super excited about sending a PR now!

**Comment by antstorm** [comment]
Got excited, here's a PR — #90

**Comment by dylanfisher** [comment]
Just curious if you were planning on changing the default behavior of the create-new-pane-if-necessary option, or adding an option to control this. Does that PR look mergable? I still preferred the old behavior,  of not creating a new pane automatically.

**Pull request closed without merging**
